name: fetch

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  fetch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: fetch
        run: |-
          curl https://ch.tetr.io/api/general/stats | jq .data > stats.json
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m fetch || exit 0
          git push
